/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adb.commands

import kotlin.test.Test
import kotlin.test.assertTrue

class BatteryInformationTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = BatteryInformationParser()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
